changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🎉 New Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
    - title: 🏎️ Performance
      labels:
        - performance
    - title: 🏗️ Build & CI
      labels:
        - build
        - ci
    - title: 📚 Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
