# Brewfile for Amiberry macOS CI
brew "cmake"
brew "sdl3"
brew "sdl3_image"
brew "mpg123"
brew "flac"
brew "libmpeg2"
brew "libserialport"
brew "portmidi"
brew "enet"
brew "libpcap"
brew "zstd"
brew "dylibbundler"
