package com.blitterstudio.amiberry.data

import android.content.Context
import com.blitterstudio.amiberry.data.model.StoragePaths
import com.blitterstudio.amiberry.data.model.EmulatorSettings
import java.io.File

/**
 * Generates .uae config files from EmulatorSettings.
 * Config key names match cfgfile_save_options() format in cfgfile.cpp.
 */
object ConfigGenerator {

	fun generate(settings: EmulatorSettings): String {
		val sb = StringBuilder()
		sb.appendLine("; Generated by Amiberry Android UI")
		sb.appendLine()

		// CPU
		sb.appendLine("cpu_model=${settings.cpuModel}")
		sb.appendLine("cpu_compatible=${settings.cpuCompatible.toCfg()}")
		sb.appendLine("cpu_24bit_addressing=${settings.address24Bit.toCfg()}")
		sb.appendLine("cpu_speed=${settings.cpuSpeed}")
		if (settings.fpuModel > 0) {
			sb.appendLine("fpu_model=${settings.fpuModel}")
		}
		if (settings.jitCacheSize > 0) {
			sb.appendLine("cachesize=${settings.jitCacheSize}")
			sb.appendLine("compfpu=${settings.jitFpu.toCfg()}")
		}

		// Chipset
		sb.appendLine("chipset=${settings.chipset}")
		sb.appendLine("immediate_blits=${settings.immediateBlits.toCfg()}")
		sb.appendLine("collision_level=${settings.collisionLevel}")
		sb.appendLine("cycle_exact=${settings.cycleExact.toCfg()}")
		sb.appendLine("ntsc=${settings.ntsc.toCfg()}")

		// Memory
		sb.appendLine("chipmem_size=${settings.chipRam}")
		sb.appendLine("bogomem_size=${settings.slowRam}")
		sb.appendLine("fastmem_size=${settings.fastRam}")
		if (settings.z3Ram > 0) {
			sb.appendLine("z3mem_size=${settings.z3Ram}")
		}

		// ROM
		if (settings.romFile.isNotEmpty()) {
			sb.appendLine("kickstart_rom_file=${settings.romFile}")
		}
		if (settings.romExtFile.isNotEmpty()) {
			sb.appendLine("kickstart_ext_rom_file=${settings.romExtFile}")
		}

		// Floppy drives
		sb.appendLine("floppy0=${settings.floppy0}")
		sb.appendLine("floppy0type=${settings.floppy0Type}")
		sb.appendLine("floppy1=${settings.floppy1}")
		sb.appendLine("floppy1type=${settings.floppy1Type}")
		sb.appendLine("floppy2=${settings.floppy2}")
		sb.appendLine("floppy2type=${settings.floppy2Type}")
		sb.appendLine("floppy3=${settings.floppy3}")
		sb.appendLine("floppy3type=${settings.floppy3Type}")

		// CD
		if (settings.cdImage.isNotEmpty()) {
			sb.appendLine("cdimage0=${settings.cdImage}")
		}

		// Sound
		sb.appendLine("sound_output=${settings.soundOutput}")
		sb.appendLine("sound_frequency=${settings.soundFreq}")
		sb.appendLine("sound_channels=${settings.soundChannels}")

		// Display
		sb.appendLine("gfx_width=${settings.gfxWidth}")
		sb.appendLine("gfx_height=${settings.gfxHeight}")
		sb.appendLine("gfx_correct_aspect=${settings.correctAspect.toCfg()}")
		sb.appendLine("gfx_auto_crop=${settings.autoCrop.toCfg()}")

		// Input
		sb.appendLine("joyport0=${settings.joyport0}")
		// When on-screen joystick is selected for port 1, omit joyport1 from config
		// and let on_screen_joystick_set_enabled() auto-assign it at runtime
		if (settings.joyport1 != "onscreen_joy") {
			sb.appendLine("joyport1=${settings.joyport1}")
		}
		// Persist the Android UI's joyport1 choice for reliable round-trip parsing
		sb.appendLine("amiberry.android_joyport1=${settings.joyport1}")

		// Amiberry-specific
		sb.appendLine("amiberry.onscreen_joystick=${settings.onScreenJoystick.toCfg()}")
		sb.appendLine("input.default_osk=${settings.onScreenKeyboard.toCfg()}")

		// Skip GUI when launched from Android native UI
		sb.appendLine("use_gui=no")

		return sb.toString()
	}

	fun writeConfig(context: Context, settings: EmulatorSettings, filename: String): File {
		val confDir = File(context.getExternalFilesDir(null), StoragePaths.CONFIGURATIONS)
		if (!confDir.exists()) confDir.mkdirs()
		val file = File(confDir, filename)
		file.writeText(generate(settings))
		return file
	}

	/**
	 * Write config and return the args needed to launch emulation with it.
	 * Uses --model for base hardware, plus --config for overrides.
	 */
	fun generateLaunchArgs(context: Context, settings: EmulatorSettings): Array<String> {
		val configFile = writeConfig(context, settings, ".current_settings.uae")
		return arrayOf(
			"--rescan-roms",
			"--model", settings.baseModel.cmdArg,
			"--config", configFile.absolutePath,
			"-G"
		)
	}

	private fun Boolean.toCfg(): String = if (this) "true" else "false"
}
