/*
* UAE - The portable Amiga emulator.
*
* This file was generated by genlinetoscr. Don't edit.
*/

STATIC_INLINE void shiftbpl1(void)
{
	bplxdat3[0] <<= 1;
}
STATIC_INLINE void shiftbpl1e(void)
{
	bplxdat3[0] <<= 1;
}
STATIC_INLINE void shiftbpl1o(void)
{
}
STATIC_INLINE void shiftbpl2(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
}
STATIC_INLINE void shiftbpl2e(void)
{
	bplxdat3[0] <<= 1;
}
STATIC_INLINE void shiftbpl2o(void)
{
	bplxdat3[1] <<= 1;
}
STATIC_INLINE void shiftbpl3(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
}
STATIC_INLINE void shiftbpl3e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
}
STATIC_INLINE void shiftbpl3o(void)
{
	bplxdat3[1] <<= 1;
}
STATIC_INLINE void shiftbpl4(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[3] <<= 1;
}
STATIC_INLINE void shiftbpl4e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
}
STATIC_INLINE void shiftbpl4o(void)
{
	bplxdat3[1] <<= 1;
	bplxdat3[3] <<= 1;
}
STATIC_INLINE void shiftbpl5(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[4] <<= 1;
}
STATIC_INLINE void shiftbpl5e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[4] <<= 1;
}
STATIC_INLINE void shiftbpl5o(void)
{
	bplxdat3[1] <<= 1;
	bplxdat3[3] <<= 1;
}
STATIC_INLINE void shiftbpl6(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[4] <<= 1;
	bplxdat3[5] <<= 1;
}
STATIC_INLINE void shiftbpl6e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[4] <<= 1;
}
STATIC_INLINE void shiftbpl6o(void)
{
	bplxdat3[1] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[5] <<= 1;
}
STATIC_INLINE void shiftbpl7(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[4] <<= 1;
	bplxdat3[5] <<= 1;
	bplxdat3[6] <<= 1;
}
STATIC_INLINE void shiftbpl7e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[4] <<= 1;
	bplxdat3[6] <<= 1;
}
STATIC_INLINE void shiftbpl7o(void)
{
	bplxdat3[1] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[5] <<= 1;
}
STATIC_INLINE void shiftbpl8(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[1] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[4] <<= 1;
	bplxdat3[5] <<= 1;
	bplxdat3[6] <<= 1;
	bplxdat3[7] <<= 1;
}
STATIC_INLINE void shiftbpl8e(void)
{
	bplxdat3[0] <<= 1;
	bplxdat3[2] <<= 1;
	bplxdat3[4] <<= 1;
	bplxdat3[6] <<= 1;
}
STATIC_INLINE void shiftbpl8o(void)
{
	bplxdat3[1] <<= 1;
	bplxdat3[3] <<= 1;
	bplxdat3[5] <<= 1;
	bplxdat3[7] <<= 1;
}
STATIC_INLINE void shiftbpl1_64(void)
{
	bplxdat3_64[0] <<= 1;
}
STATIC_INLINE void shiftbpl1e_64(void)
{
	bplxdat3_64[0] <<= 1;
}
STATIC_INLINE void shiftbpl1o_64(void)
{
}
STATIC_INLINE void shiftbpl2_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
}
STATIC_INLINE void shiftbpl2e_64(void)
{
	bplxdat3_64[0] <<= 1;
}
STATIC_INLINE void shiftbpl2o_64(void)
{
	bplxdat3_64[1] <<= 1;
}
STATIC_INLINE void shiftbpl3_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
}
STATIC_INLINE void shiftbpl3e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
}
STATIC_INLINE void shiftbpl3o_64(void)
{
	bplxdat3_64[1] <<= 1;
}
STATIC_INLINE void shiftbpl4_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[3] <<= 1;
}
STATIC_INLINE void shiftbpl4e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
}
STATIC_INLINE void shiftbpl4o_64(void)
{
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[3] <<= 1;
}
STATIC_INLINE void shiftbpl5_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[4] <<= 1;
}
STATIC_INLINE void shiftbpl5e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[4] <<= 1;
}
STATIC_INLINE void shiftbpl5o_64(void)
{
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[3] <<= 1;
}
STATIC_INLINE void shiftbpl6_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[4] <<= 1;
	bplxdat3_64[5] <<= 1;
}
STATIC_INLINE void shiftbpl6e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[4] <<= 1;
}
STATIC_INLINE void shiftbpl6o_64(void)
{
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[5] <<= 1;
}
STATIC_INLINE void shiftbpl7_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[4] <<= 1;
	bplxdat3_64[5] <<= 1;
	bplxdat3_64[6] <<= 1;
}
STATIC_INLINE void shiftbpl7e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[4] <<= 1;
	bplxdat3_64[6] <<= 1;
}
STATIC_INLINE void shiftbpl7o_64(void)
{
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[5] <<= 1;
}
STATIC_INLINE void shiftbpl8_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[4] <<= 1;
	bplxdat3_64[5] <<= 1;
	bplxdat3_64[6] <<= 1;
	bplxdat3_64[7] <<= 1;
}
STATIC_INLINE void shiftbpl8e_64(void)
{
	bplxdat3_64[0] <<= 1;
	bplxdat3_64[2] <<= 1;
	bplxdat3_64[4] <<= 1;
	bplxdat3_64[6] <<= 1;
}
STATIC_INLINE void shiftbpl8o_64(void)
{
	bplxdat3_64[1] <<= 1;
	bplxdat3_64[3] <<= 1;
	bplxdat3_64[5] <<= 1;
	bplxdat3_64[7] <<= 1;
}
STATIC_INLINE uae_u8 getbpl1(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	return v;
}
STATIC_INLINE uae_u8 getbpl2(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	return v;
}
STATIC_INLINE uae_u8 getbpl3(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	return v;
}
STATIC_INLINE uae_u8 getbpl4(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	v |= ((bplxdat3[3] >> 15) & 1) << 3;
	return v;
}
STATIC_INLINE uae_u8 getbpl5(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	v |= ((bplxdat3[3] >> 15) & 1) << 3;
	v |= ((bplxdat3[4] >> 15) & 1) << 4;
	return v;
}
STATIC_INLINE uae_u8 getbpl6(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	v |= ((bplxdat3[3] >> 15) & 1) << 3;
	v |= ((bplxdat3[4] >> 15) & 1) << 4;
	v |= ((bplxdat3[5] >> 15) & 1) << 5;
	return v;
}
STATIC_INLINE uae_u8 getbpl7(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	v |= ((bplxdat3[3] >> 15) & 1) << 3;
	v |= ((bplxdat3[4] >> 15) & 1) << 4;
	v |= ((bplxdat3[5] >> 15) & 1) << 5;
	v |= ((bplxdat3[6] >> 15) & 1) << 6;
	return v;
}
STATIC_INLINE uae_u8 getbpl8(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 15) & 1) << 0;
	v |= ((bplxdat3[1] >> 15) & 1) << 1;
	v |= ((bplxdat3[2] >> 15) & 1) << 2;
	v |= ((bplxdat3[3] >> 15) & 1) << 3;
	v |= ((bplxdat3[4] >> 15) & 1) << 4;
	v |= ((bplxdat3[5] >> 15) & 1) << 5;
	v |= ((bplxdat3[6] >> 15) & 1) << 6;
	v |= ((bplxdat3[7] >> 15) & 1) << 7;
	return v;
}
STATIC_INLINE uae_u8 getbpl1_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	return v;
}
STATIC_INLINE uae_u8 getbpl2_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	return v;
}
STATIC_INLINE uae_u8 getbpl3_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	return v;
}
STATIC_INLINE uae_u8 getbpl4_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	v |= ((bplxdat3[3] >> 31) & 1) << 3;
	return v;
}
STATIC_INLINE uae_u8 getbpl5_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	v |= ((bplxdat3[3] >> 31) & 1) << 3;
	v |= ((bplxdat3[4] >> 31) & 1) << 4;
	return v;
}
STATIC_INLINE uae_u8 getbpl6_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	v |= ((bplxdat3[3] >> 31) & 1) << 3;
	v |= ((bplxdat3[4] >> 31) & 1) << 4;
	v |= ((bplxdat3[5] >> 31) & 1) << 5;
	return v;
}
STATIC_INLINE uae_u8 getbpl7_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	v |= ((bplxdat3[3] >> 31) & 1) << 3;
	v |= ((bplxdat3[4] >> 31) & 1) << 4;
	v |= ((bplxdat3[5] >> 31) & 1) << 5;
	v |= ((bplxdat3[6] >> 31) & 1) << 6;
	return v;
}
STATIC_INLINE uae_u8 getbpl8_32(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3[0] >> 31) & 1) << 0;
	v |= ((bplxdat3[1] >> 31) & 1) << 1;
	v |= ((bplxdat3[2] >> 31) & 1) << 2;
	v |= ((bplxdat3[3] >> 31) & 1) << 3;
	v |= ((bplxdat3[4] >> 31) & 1) << 4;
	v |= ((bplxdat3[5] >> 31) & 1) << 5;
	v |= ((bplxdat3[6] >> 31) & 1) << 6;
	v |= ((bplxdat3[7] >> 31) & 1) << 7;
	return v;
}
STATIC_INLINE uae_u8 getbpl1_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	return v;
}
STATIC_INLINE uae_u8 getbpl2_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	return v;
}
STATIC_INLINE uae_u8 getbpl3_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	return v;
}
STATIC_INLINE uae_u8 getbpl4_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	v |= ((bplxdat3_64[3] >> 63) & 1) << 3;
	return v;
}
STATIC_INLINE uae_u8 getbpl5_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	v |= ((bplxdat3_64[3] >> 63) & 1) << 3;
	v |= ((bplxdat3_64[4] >> 63) & 1) << 4;
	return v;
}
STATIC_INLINE uae_u8 getbpl6_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	v |= ((bplxdat3_64[3] >> 63) & 1) << 3;
	v |= ((bplxdat3_64[4] >> 63) & 1) << 4;
	v |= ((bplxdat3_64[5] >> 63) & 1) << 5;
	return v;
}
STATIC_INLINE uae_u8 getbpl7_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	v |= ((bplxdat3_64[3] >> 63) & 1) << 3;
	v |= ((bplxdat3_64[4] >> 63) & 1) << 4;
	v |= ((bplxdat3_64[5] >> 63) & 1) << 5;
	v |= ((bplxdat3_64[6] >> 63) & 1) << 6;
	return v;
}
STATIC_INLINE uae_u8 getbpl8_64(void)
{
	uae_u8 v = 0;
	v |= ((bplxdat3_64[0] >> 63) & 1) << 0;
	v |= ((bplxdat3_64[1] >> 63) & 1) << 1;
	v |= ((bplxdat3_64[2] >> 63) & 1) << 2;
	v |= ((bplxdat3_64[3] >> 63) & 1) << 3;
	v |= ((bplxdat3_64[4] >> 63) & 1) << 4;
	v |= ((bplxdat3_64[5] >> 63) & 1) << 5;
	v |= ((bplxdat3_64[6] >> 63) & 1) << 6;
	v |= ((bplxdat3_64[7] >> 63) & 1) << 7;
	return v;
}
STATIC_INLINE void copybpl1(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl2(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl3(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl4(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl5(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl6(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl7(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	if (denise_planes >= 7) {
		bplxdat3[6] = bplxdat2[6];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl8(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	if (denise_planes >= 7) {
		bplxdat3[6] = bplxdat2[6];
	}
	if (denise_planes >= 8) {
		bplxdat3[7] = bplxdat2[7];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl1e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl2e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl3e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl4e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl5e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl6e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl7e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	if (denise_planes >= 7) {
		bplxdat3[6] = bplxdat2[6];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl8e(void)
{
	if (denise_planes >= 1) {
		bplxdat3[0] = bplxdat2[0];
	}
	if (denise_planes >= 3) {
		bplxdat3[2] = bplxdat2[2];
	}
	if (denise_planes >= 5) {
		bplxdat3[4] = bplxdat2[4];
	}
	if (denise_planes >= 7) {
		bplxdat3[6] = bplxdat2[6];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl1o(void)
{
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl2o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl3o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl4o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl5o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl6o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl7o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl8o(void)
{
	if (denise_planes >= 2) {
		bplxdat3[1] = bplxdat2[1];
	}
	if (denise_planes >= 4) {
		bplxdat3[3] = bplxdat2[3];
	}
	if (denise_planes >= 6) {
		bplxdat3[5] = bplxdat2[5];
	}
	if (denise_planes >= 8) {
		bplxdat3[7] = bplxdat2[7];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl1_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl2_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl3_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl4_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl5_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl6_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl7_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	if (denise_planes >= 7) {
		bplxdat3_64[6] = bplxdat2_64[6];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl8_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	if (denise_planes >= 7) {
		bplxdat3_64[6] = bplxdat2_64[6];
	}
	if (denise_planes >= 8) {
		bplxdat3_64[7] = bplxdat2_64[7];
	}
	bpldat_copy[0] = false;
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl1e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl2e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl3e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl4e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl5e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl6e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl7e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	if (denise_planes >= 7) {
		bplxdat3_64[6] = bplxdat2_64[6];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl8e_64(void)
{
	if (denise_planes >= 1) {
		bplxdat3_64[0] = bplxdat2_64[0];
	}
	if (denise_planes >= 3) {
		bplxdat3_64[2] = bplxdat2_64[2];
	}
	if (denise_planes >= 5) {
		bplxdat3_64[4] = bplxdat2_64[4];
	}
	if (denise_planes >= 7) {
		bplxdat3_64[6] = bplxdat2_64[6];
	}
	bpldat_copy[0] = false;
}
STATIC_INLINE void copybpl1o_64(void)
{
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl2o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl3o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl4o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl5o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl6o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl7o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	bpldat_copy[1] = false;
}
STATIC_INLINE void copybpl8o_64(void)
{
	if (denise_planes >= 2) {
		bplxdat3_64[1] = bplxdat2_64[1];
	}
	if (denise_planes >= 4) {
		bplxdat3_64[3] = bplxdat2_64[3];
	}
	if (denise_planes >= 6) {
		bplxdat3_64[5] = bplxdat2_64[5];
	}
	if (denise_planes >= 8) {
		bplxdat3_64[7] = bplxdat2_64[7];
	}
	bpldat_copy[1] = false;
}
